// <auto-generated />
using System;
using Forgettable.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Forgettable.Migrations
{
    [DbContext(typeof(ForgettableDbContext))]
    [Migration("20261004200157_BoilerService")]
    partial class BoilerService
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Forgettable.Models.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ItemId"));

                    b.Property<bool>("AutoRenew")
                        .HasColumnType("boolean");

                    b.Property<bool>("Booked")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<int?>("PaperlessDocumentId")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.HasKey("ItemId");

                    b.ToTable("Items");

                    b.HasDiscriminator<string>("Type").HasValue("Item");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Forgettable.Models.Items.BoilerService", b =>
                {
                    b.HasBaseType("Forgettable.Models.Item");

                    b.HasDiscriminator().HasValue("BoilerService");
                });

            modelBuilder.Entity("Forgettable.Models.Items.ChimneySweep", b =>
                {
                    b.HasBaseType("Forgettable.Models.Item");

                    b.HasDiscriminator().HasValue("ChimneySweep");
                });

            modelBuilder.Entity("Forgettable.Models.Items.DrivingLicence", b =>
                {
                    b.HasBaseType("Forgettable.Models.Item");

                    b.Property<string>("LicenceNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("DrivingLicence");
                });

            modelBuilder.Entity("Forgettable.Models.Items.GHIC", b =>
                {
                    b.HasBaseType("Forgettable.Models.Item");

                    b.Property<string>("PersonalIdNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("GHIC");
                });

            modelBuilder.Entity("Forgettable.Models.Items.HomeInsurance", b =>
                {
                    b.HasBaseType("Forgettable.Models.Item");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("HomeInsurance");
                });

            modelBuilder.Entity("Forgettable.Models.Items.MOT", b =>
                {
                    b.HasBaseType("Forgettable.Models.Item");

                    b.Property<string>("Registration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("MOT");
                });

            modelBuilder.Entity("Forgettable.Models.Items.Mortgage", b =>
                {
                    b.HasBaseType("Forgettable.Models.Item");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Lender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Rate")
                        .HasColumnType("numeric");

                    b.HasDiscriminator().HasValue("Mortgage");
                });

            modelBuilder.Entity("Forgettable.Models.Items.Passport", b =>
                {
                    b.HasBaseType("Forgettable.Models.Item");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Passport");
                });

            modelBuilder.Entity("Forgettable.Models.Items.Railcard", b =>
                {
                    b.HasBaseType("Forgettable.Models.Item");

                    b.Property<string>("RailcardNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RailcardType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Railcard");
                });

            modelBuilder.Entity("Forgettable.Models.Items.VehicleFinance", b =>
                {
                    b.HasBaseType("Forgettable.Models.Item");

                    b.Property<string>("AgreementNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("FinalPayment")
                        .HasColumnType("numeric");

                    b.Property<int>("FinanceType")
                        .HasColumnType("integer");

                    b.Property<string>("Lender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("MileageAllowance")
                        .HasColumnType("integer");

                    b.Property<string>("Registration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("Items", t =>
                        {
                            t.Property("Lender")
                                .HasColumnName("VehicleFinance_Lender");

                            t.Property("Registration")
                                .HasColumnName("VehicleFinance_Registration");
                        });

                    b.HasDiscriminator().HasValue("VehicleFinance");
                });

            modelBuilder.Entity("Forgettable.Models.Items.VehicleInsurance", b =>
                {
                    b.HasBaseType("Forgettable.Models.Item");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Registration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("Items", t =>
                        {
                            t.Property("PolicyNumber")
                                .HasColumnName("VehicleInsurance_PolicyNumber");

                            t.Property("Provider")
                                .HasColumnName("VehicleInsurance_Provider");

                            t.Property("Registration")
                                .HasColumnName("VehicleInsurance_Registration");
                        });

                    b.HasDiscriminator().HasValue("VehicleInsurance");
                });

            modelBuilder.Entity("Forgettable.Models.Items.VehicleService", b =>
                {
                    b.HasBaseType("Forgettable.Models.Item");

                    b.Property<string>("Registration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("Items", t =>
                        {
                            t.Property("Registration")
                                .HasColumnName("VehicleService_Registration");
                        });

                    b.HasDiscriminator().HasValue("VehicleService");
                });

            modelBuilder.Entity("Forgettable.Models.Items.VehicleTax", b =>
                {
                    b.HasBaseType("Forgettable.Models.Item");

                    b.Property<string>("Registration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("Items", t =>
                        {
                            t.Property("Registration")
                                .HasColumnName("VehicleTax_Registration");
                        });

                    b.HasDiscriminator().HasValue("VehicleTax");
                });
#pragma warning restore 612, 618
        }
    }
}
