// <auto-generated />
using System;
using Forgettable.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Forgettable.Migrations
{
    [DbContext(typeof(ForgettableDbContext))]
    [Migration("20261004143556_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Forgettable.Models.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ItemId"));

                    b.Property<bool>("AutoRenew")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.HasKey("ItemId");

                    b.ToTable("Items");

                    b.HasDiscriminator<string>("Type").HasValue("Item");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Forgettable.Models.DrivingLicence", b =>
                {
                    b.HasBaseType("Forgettable.Models.Item");

                    b.Property<string>("DriverNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("DrivingLicence");
                });

            modelBuilder.Entity("Forgettable.Models.MOT", b =>
                {
                    b.HasBaseType("Forgettable.Models.Item");

                    b.Property<string>("Registration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("MOT");
                });

            modelBuilder.Entity("Forgettable.Models.Passport", b =>
                {
                    b.HasBaseType("Forgettable.Models.Item");

                    b.HasDiscriminator().HasValue("Passport");
                });
#pragma warning restore 612, 618
        }
    }
}
